import type {Metadata} from "next";
import {Jost} from "next/font/google";
import Providers from "./providers";
import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "York Dental Suite",
  description: "Generated by create next app and WordPress",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jost.variable} font-main`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
