import type {Metadata} from "next";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "York Dental Suite",
  description: "Generated by create next app and WordPress",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
